name: 更新题解数量

on:
  push:
    paths:
      - '**.py'        # any .py file
      - '**.java'      # Java
      - '**.cpp'       # C++
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 统计文件数量并更新 README
        run: |
          COUNT=$(find . -name "*.py" -type f | wc -l | xargs)
          
          sed -i "s/<!-- SOL_COUNT -->.*/<!-- SOL_COUNT --> $COUNT/" README.md
          
          cat README.md

      - name: 提交更改回仓库
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          # 只有文件确实被修改了才提交，否则忽略
          git diff --staged --quiet || git commit -m "Update # of Problem Solved"
          git push